version: '3'
services:
  chat-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: unclegpts/partnerai-api
    container_name: partnerai-api
    restart: always
    network_mode: host
    ports:
      - "3002:3000"
    environment:
      - TZ=Asia/Shanghai
      - REDIS_CONN_STRING=redis://default:123@localhost:6379
      - SQL_DSN=partnerai-api:zZPRDwnidSaefdDT@tcp(38.6.221.23:3306)/partnerai-api
      - SESSION_SECRET=Wwww1314  # 修改为随机字符串
      - SYNC_FREQUENCY=60
      - CHANNEL_TEST_FREQUENCY=1440
      - GLOBAL_API_RATE_LIMIT=180
      - GLOBAL_WEB_RATE_LIMIT=60
#     - NODE_TYPE=slave  # 多机部署时从节点取消注释该行
#     - SYNC_FREQUENCY=60  # 需要定期从数据库加载数据时取消注释该行
#     - FRONTEND_BASE_URL=https://openai.justsong.cn  # 多机部署时从节点取消注释该行
    volumes:
      - /data/one-api1:/data
